//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIS.GME.Dsml.SignLanguage.Interfaces
{
	
	
	/// <summary>
	///<para>This API code is compatible with the following paradigm:</para>
	///<para> - Name: SignLanguage</para>
	///<para> - Guid: {344D86A3-E082-4C85-AE04-B49EF1C905DA}</para>
	///<para>Additional information: </para>
	///<para> - Date: 7/21/2014 11:46:24 AM</para>
	///<para> - Author: </para>
	///<para> - Version: </para>
	///<para> - Comment: </para>
	///</summary>
	///
	/// <summary>
	/// <para>RootFolder interface</para>
	/// </summary>
	public interface RootFolder : ISIS.GME.Common.Interfaces.RootFolder
	{
		
		/// <summary>
		///<para></para>
		///<para></para>
		///</summary>
		ISIS.GME.Dsml.SignLanguage.Classes.RootFolder.InfoClass Info
		{
			get;
		}
		
		/// <summary>
		///<para></para>
		///<para></para>
		///</summary>
		new global::System.Collections.Generic.Dictionary<int, global::System.Type> MetaRefs
		{
			get;
		}
		
		/// <summary>
		///<para>Contains the library's connection string if this object is an attached library.</para>
		///<para></para>
		///</summary>
		string LibraryName
		{
			get;
		}
		
		/// <summary>
		///<para>Contains the domain specific attached libraries.</para>
		///<para></para>
		///</summary>
		global::System.Collections.Generic.IEnumerable<ISIS.GME.Dsml.SignLanguage.Interfaces.RootFolder> LibraryCollection
		{
			get;
		}
		
		/// <summary>
		///<para>Contains the domain specific child objects.</para>
		///<para></para>
		///</summary>
		Classes.RootFolder.ChildrenClass Children
		{
			get;
		}
		
		/// <summary>
		///<para>Contains all the domain specific child objects.</para>
		///<para></para>
		///</summary>
		new global::System.Collections.Generic.IEnumerable<ISIS.GME.Common.Interfaces.Base> AllChildren
		{
			get;
		}
	}
	
	/// <summary>
	/// <para>ParkingSign interface</para>
	/// </summary>
	public interface ParkingSign : ISIS.GME.Common.Interfaces.Atom
	{
		
		/// <summary>
		///<para>Contains the domain specific source end point of this connection.</para>
		///<para></para>
		///</summary>
		global::System.Collections.Generic.IEnumerable<ISIS.GME.Common.Interfaces.Connection> AllSrcConnections
		{
			get;
		}
		
		/// <summary>
		///<para>Retrieves all connections, which have this object as a DESTINATION.</para>
		///<para></para>
		///</summary>
		ISIS.GME.Dsml.SignLanguage.Classes.ParkingSign.SrcConnectionsClass SrcConnections
		{
			get;
		}
		
		/// <summary>
		///<para>Contains the domain specific destination end point of this connection.</para>
		///<para></para>
		///</summary>
		global::System.Collections.Generic.IEnumerable<ISIS.GME.Common.Interfaces.Connection> AllDstConnections
		{
			get;
		}
		
		/// <summary>
		///<para>Retrieves all connections, which have this object as a SOURCE.</para>
		///<para></para>
		///</summary>
		ISIS.GME.Dsml.SignLanguage.Classes.ParkingSign.DstConnectionsClass DstConnections
		{
			get;
		}
		
		/// <summary>
		///<para>the object that is at the farthest position within the chain of base objects (i.e. the one which is not derived from anything).</para>
		///<para> NULL if the object is not derived.</para>
		///</summary>
		ISIS.GME.Dsml.SignLanguage.Interfaces.ParkingSign ArcheType
		{
			get;
		}
		
		/// <summary>
		///<para>Contains the domain specific attributes.</para>
		///<para></para>
		///</summary>
		ISIS.GME.Dsml.SignLanguage.Classes.ParkingSign.AttributesClass Attributes
		{
			get;
		}
		
		/// <summary>
		///<para></para>
		///<para></para>
		///</summary>
		global::System.Collections.Generic.IEnumerable<ISIS.GME.Common.Interfaces.FCO> AllReferencedBy
		{
			get;
		}
		
		/// <summary>
		///<para></para>
		///<para></para>
		///</summary>
		ISIS.GME.Dsml.SignLanguage.Classes.ParkingSign.ReferencedByClass ReferencedBy
		{
			get;
		}
		
		/// <summary>
		///<para></para>
		///<para></para>
		///</summary>
		global::System.Collections.Generic.IEnumerable<ISIS.GME.Common.Interfaces.FCO> AllMembersOfSet
		{
			get;
		}
		
		/// <summary>
		///<para></para>
		///<para></para>
		///</summary>
		ISIS.GME.Dsml.SignLanguage.Classes.ParkingSign.MembersOfSetClass MembersOfSet
		{
			get;
		}
	}
	
	/// <summary>
	/// <para>FloodSign interface</para>
	/// </summary>
	public interface FloodSign : ISIS.GME.Common.Interfaces.Atom
	{
		
		/// <summary>
		///<para>Contains the domain specific source end point of this connection.</para>
		///<para></para>
		///</summary>
		global::System.Collections.Generic.IEnumerable<ISIS.GME.Common.Interfaces.Connection> AllSrcConnections
		{
			get;
		}
		
		/// <summary>
		///<para>Retrieves all connections, which have this object as a DESTINATION.</para>
		///<para></para>
		///</summary>
		ISIS.GME.Dsml.SignLanguage.Classes.FloodSign.SrcConnectionsClass SrcConnections
		{
			get;
		}
		
		/// <summary>
		///<para>Contains the domain specific destination end point of this connection.</para>
		///<para></para>
		///</summary>
		global::System.Collections.Generic.IEnumerable<ISIS.GME.Common.Interfaces.Connection> AllDstConnections
		{
			get;
		}
		
		/// <summary>
		///<para>Retrieves all connections, which have this object as a SOURCE.</para>
		///<para></para>
		///</summary>
		ISIS.GME.Dsml.SignLanguage.Classes.FloodSign.DstConnectionsClass DstConnections
		{
			get;
		}
		
		/// <summary>
		///<para>the object that is at the farthest position within the chain of base objects (i.e. the one which is not derived from anything).</para>
		///<para> NULL if the object is not derived.</para>
		///</summary>
		ISIS.GME.Dsml.SignLanguage.Interfaces.FloodSign ArcheType
		{
			get;
		}
		
		/// <summary>
		///<para>Contains the domain specific attributes.</para>
		///<para></para>
		///</summary>
		ISIS.GME.Dsml.SignLanguage.Classes.FloodSign.AttributesClass Attributes
		{
			get;
		}
		
		/// <summary>
		///<para></para>
		///<para></para>
		///</summary>
		global::System.Collections.Generic.IEnumerable<ISIS.GME.Common.Interfaces.FCO> AllReferencedBy
		{
			get;
		}
		
		/// <summary>
		///<para></para>
		///<para></para>
		///</summary>
		ISIS.GME.Dsml.SignLanguage.Classes.FloodSign.ReferencedByClass ReferencedBy
		{
			get;
		}
		
		/// <summary>
		///<para></para>
		///<para></para>
		///</summary>
		global::System.Collections.Generic.IEnumerable<ISIS.GME.Common.Interfaces.FCO> AllMembersOfSet
		{
			get;
		}
		
		/// <summary>
		///<para></para>
		///<para></para>
		///</summary>
		ISIS.GME.Dsml.SignLanguage.Classes.FloodSign.MembersOfSetClass MembersOfSet
		{
			get;
		}
	}
	
	/// <summary>
	/// <para>StreetSign interface</para>
	/// </summary>
	public interface StreetSign : ISIS.GME.Common.Interfaces.Atom
	{
		
		/// <summary>
		///<para>Contains the domain specific source end point of this connection.</para>
		///<para></para>
		///</summary>
		global::System.Collections.Generic.IEnumerable<ISIS.GME.Common.Interfaces.Connection> AllSrcConnections
		{
			get;
		}
		
		/// <summary>
		///<para>Retrieves all connections, which have this object as a DESTINATION.</para>
		///<para></para>
		///</summary>
		ISIS.GME.Dsml.SignLanguage.Classes.StreetSign.SrcConnectionsClass SrcConnections
		{
			get;
		}
		
		/// <summary>
		///<para>Contains the domain specific destination end point of this connection.</para>
		///<para></para>
		///</summary>
		global::System.Collections.Generic.IEnumerable<ISIS.GME.Common.Interfaces.Connection> AllDstConnections
		{
			get;
		}
		
		/// <summary>
		///<para>Retrieves all connections, which have this object as a SOURCE.</para>
		///<para></para>
		///</summary>
		ISIS.GME.Dsml.SignLanguage.Classes.StreetSign.DstConnectionsClass DstConnections
		{
			get;
		}
		
		/// <summary>
		///<para>the object that is at the farthest position within the chain of base objects (i.e. the one which is not derived from anything).</para>
		///<para> NULL if the object is not derived.</para>
		///</summary>
		ISIS.GME.Dsml.SignLanguage.Interfaces.StreetSign ArcheType
		{
			get;
		}
		
		/// <summary>
		///<para>Contains the domain specific attributes.</para>
		///<para></para>
		///</summary>
		ISIS.GME.Dsml.SignLanguage.Classes.StreetSign.AttributesClass Attributes
		{
			get;
		}
		
		/// <summary>
		///<para></para>
		///<para></para>
		///</summary>
		global::System.Collections.Generic.IEnumerable<ISIS.GME.Common.Interfaces.FCO> AllReferencedBy
		{
			get;
		}
		
		/// <summary>
		///<para></para>
		///<para></para>
		///</summary>
		ISIS.GME.Dsml.SignLanguage.Classes.StreetSign.ReferencedByClass ReferencedBy
		{
			get;
		}
		
		/// <summary>
		///<para></para>
		///<para></para>
		///</summary>
		global::System.Collections.Generic.IEnumerable<ISIS.GME.Common.Interfaces.FCO> AllMembersOfSet
		{
			get;
		}
		
		/// <summary>
		///<para></para>
		///<para></para>
		///</summary>
		ISIS.GME.Dsml.SignLanguage.Classes.StreetSign.MembersOfSetClass MembersOfSet
		{
			get;
		}
	}
	
	/// <summary>
	/// <para>Signs interface</para>
	/// </summary>
	public interface Signs : ISIS.GME.Common.Interfaces.Model
	{
		
		/// <summary>
		///<para>Contains the domain specific source end point of this connection.</para>
		///<para></para>
		///</summary>
		global::System.Collections.Generic.IEnumerable<ISIS.GME.Common.Interfaces.Connection> AllSrcConnections
		{
			get;
		}
		
		/// <summary>
		///<para>Retrieves all connections, which have this object as a DESTINATION.</para>
		///<para></para>
		///</summary>
		ISIS.GME.Dsml.SignLanguage.Classes.Signs.SrcConnectionsClass SrcConnections
		{
			get;
		}
		
		/// <summary>
		///<para>Contains the domain specific destination end point of this connection.</para>
		///<para></para>
		///</summary>
		global::System.Collections.Generic.IEnumerable<ISIS.GME.Common.Interfaces.Connection> AllDstConnections
		{
			get;
		}
		
		/// <summary>
		///<para>Retrieves all connections, which have this object as a SOURCE.</para>
		///<para></para>
		///</summary>
		ISIS.GME.Dsml.SignLanguage.Classes.Signs.DstConnectionsClass DstConnections
		{
			get;
		}
		
		/// <summary>
		///<para>the object that is at the farthest position within the chain of base objects (i.e. the one which is not derived from anything).</para>
		///<para> NULL if the object is not derived.</para>
		///</summary>
		ISIS.GME.Dsml.SignLanguage.Interfaces.Signs ArcheType
		{
			get;
		}
		
		/// <summary>
		///<para>Contains the domain specific attributes.</para>
		///<para></para>
		///</summary>
		ISIS.GME.Dsml.SignLanguage.Classes.Signs.AttributesClass Attributes
		{
			get;
		}
		
		/// <summary>
		///<para>Contains the domain specific child objects.</para>
		///<para></para>
		///</summary>
		Classes.Signs.ChildrenClass Children
		{
			get;
		}
		
		/// <summary>
		///<para>Contains all the domain specific child objects.</para>
		///<para></para>
		///</summary>
		new global::System.Collections.Generic.IEnumerable<ISIS.GME.Common.Interfaces.Base> AllChildren
		{
			get;
		}
		
		/// <summary>
		///<para></para>
		///<para></para>
		///</summary>
		global::System.Collections.Generic.IEnumerable<ISIS.GME.Common.Interfaces.FCO> AllReferencedBy
		{
			get;
		}
		
		/// <summary>
		///<para></para>
		///<para></para>
		///</summary>
		ISIS.GME.Dsml.SignLanguage.Classes.Signs.ReferencedByClass ReferencedBy
		{
			get;
		}
		
		/// <summary>
		///<para></para>
		///<para></para>
		///</summary>
		global::System.Collections.Generic.IEnumerable<ISIS.GME.Common.Interfaces.FCO> AllMembersOfSet
		{
			get;
		}
		
		/// <summary>
		///<para></para>
		///<para></para>
		///</summary>
		ISIS.GME.Dsml.SignLanguage.Classes.Signs.MembersOfSetClass MembersOfSet
		{
			get;
		}
	}
}
